version: '3.8'
services:
    app:
        container_name: News-Serve
        build:
            context: .
            dockerfile: docker/Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - redis

    redis:
        platform: linux/arm64
        image: redis:latest
        container_name: News-redis
        ports:
            - '55010:6379'
        volumes:
            - ./docker/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]

    mysql8:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        container_name: News-mysql8
        restart: unless-stopped
        ports:
            - '8878:3306'
        environment:
            MYSQL_USER: 'db_user'
            MYSQL_PASSWORD: '123456'
            MYSQL_ROOT_PASSWORD: '123456'
            MYSQL_DATABASE: 'news-aggregator'
        volumes:
            - './docker/data/mysql8:/var/lib/mysql'
            - './docker/sql/:/docker-entrypoint-initdb.d'

    horizon:
        container_name: News-Horizon
        build:
            context: .
            dockerfile: docker/Dockerfile
        command: 'php artisan horizon'
        volumes:
            - .:/app
        depends_on:
            - redis

    scheduler:
        container_name: News-Scheduler
        build:
            context: .
            dockerfile: docker/Dockerfile
        command: 'php artisan schedule:work'
        volumes:
            - .:/app
        depends_on:
            - redis

volumes:
    db:
        driver: local
